"""
Post 8 — Composite chart: Cargo asymmetry + Port concentration (split: imports + exports)
Reads CSVs from Outputs/post8/ (generated by post8_china_brazil_analysis.py)
"""
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from matplotlib import rcParams

rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Arial', 'Liberation Sans', 'DejaVu Sans']

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "Outputs" / "post8"
OUT_PNG = OUT_DIR / "post8_china_brazil_chart.png"

# ============================================================================
# Palette (consistent with Posts 6 + 7)
# ============================================================================
TEXT_DARK = '#0F1419'
TEXT_GRAY = '#3D4F5E'
TEXT_LIGHT = '#5D6D7E'
TEXT_SOURCE = '#7B8A9A'
DIVIDER = '#D5DBE0'

# Cargo category colors
COLOR_RAW = '#A0522D'        # sienna / earth — commodity
COLOR_SEMI = '#6B8B9E'       # slate gray — intermediate
COLOR_FINISHED = '#1F4E79'   # deep navy — manufactured

# Port bar colors
COLOR_PORT = '#1F4E79'
COLOR_PORT_TOP = '#0F2D4A'   # slightly darker for top-1 port

# ============================================================================
# Load data
# ============================================================================
br_to_cn_cat = pd.read_csv(OUT_DIR / "br_to_cn_by_category.csv", sep=";", encoding="utf-8-sig")
cn_to_br_cat = pd.read_csv(OUT_DIR / "cn_to_br_by_category.csv", sep=";", encoding="utf-8-sig")
ports_imports = pd.read_csv(OUT_DIR / "cn_to_br_ports_top10.csv", sep=";", encoding="utf-8-sig")
ports_exports = pd.read_csv(OUT_DIR / "br_to_cn_ports_top10.csv", sep=";", encoding="utf-8-sig")
summary = pd.read_csv(OUT_DIR / "summary_metrics.csv", sep=";", encoding="utf-8-sig")

HHI_IMP = summary.loc[summary["metric"] == "HHI_imports", "value"].iloc[0]
HHI_EXP = summary.loc[summary["metric"] == "HHI_exports", "value"].iloc[0]


def get_shares(df):
    d = df.set_index("category")["fob_share_pct"].to_dict()
    return d.get("raw", 0), d.get("semi", 0), d.get("finished", 0)


br_raw, br_semi, br_finished = get_shares(br_to_cn_cat)
cn_raw, cn_semi, cn_finished = get_shares(cn_to_br_cat)

# ============================================================================
# Build figure
# ============================================================================
fig = plt.figure(figsize=(12, 6.3), dpi=100)
fig.patch.set_facecolor('#FFFFFF')

# --- TITLE block (top)
fig.text(0.5, 0.93,
         "Brazil-China: structural asymmetry meets port concentration.",
         ha='center', fontsize=17, fontweight='bold', color=TEXT_DARK)
fig.text(0.5, 0.885,
         "Brazil exports raw; China exports finished — through structurally different ports.",
         ha='center', fontsize=13, color=TEXT_GRAY)
fig.text(0.5, 0.835,
         "Brazil–China container trade 2025  ·  ComexStat (maritime only)",
         ha='center', fontsize=10, color=TEXT_LIGHT, style='italic')

# --- Top divider
fig.add_artist(plt.Line2D([0.06, 0.94], [0.79, 0.79],
                          color=DIVIDER, linewidth=0.8,
                          transform=fig.transFigure))

# ============================================================================
# PANEL LEFT — Cargo asymmetry (100% stacked horizontal bars)
# ============================================================================
ax_left = fig.add_axes([0.13, 0.23, 0.42, 0.50])
ax_left.set_facecolor('#FFFFFF')
ax_left.set_ylim(-0.5, 10.5)

# Mini panel title
fig.text(0.34, 0.755,
         "Cargo composition by direction (% of FOB)",
         ha='center', fontsize=11, color=TEXT_DARK, fontweight='bold')

directions = ["China → Brazil\nimports", "Brazil → China\nexports"]
BAR_HEIGHT = 4.0
TOP_SANTOS = 10.0
TOP_IMPORTS_TARGET = 4.8

y_pos = [TOP_IMPORTS_TARGET - BAR_HEIGHT / 2,
         TOP_SANTOS - BAR_HEIGHT / 2]

raw_vals = [cn_raw, br_raw]
semi_vals = [cn_semi, br_semi]
finished_vals = [cn_finished, br_finished]

ax_left.barh(y_pos, raw_vals, color=COLOR_RAW, edgecolor='white', linewidth=0.5, height=BAR_HEIGHT, label='Raw / commodities')
ax_left.barh(y_pos, semi_vals, left=raw_vals, color=COLOR_SEMI, edgecolor='white', linewidth=0.5, height=BAR_HEIGHT, label='Semi-processed')
ax_left.barh(y_pos, finished_vals,
             left=[r + s for r, s in zip(raw_vals, semi_vals)],
             color=COLOR_FINISHED, edgecolor='white', linewidth=0.5, height=BAR_HEIGHT, label='Finished goods')


def add_segment_labels(values, lefts, color='white'):
    for i, (v, l) in enumerate(zip(values, lefts)):
        if v >= 3.0:
            ax_left.text(l + v / 2, y_pos[i], f'{v:.0f}%',
                         ha='center', va='center',
                         fontsize=10, color=color, fontweight='bold')


add_segment_labels(raw_vals, [0, 0])
add_segment_labels(semi_vals, raw_vals)
add_segment_labels(finished_vals, [r + s for r, s in zip(raw_vals, semi_vals)])

ax_left.set_yticks(y_pos)
y_labels = ax_left.set_yticklabels(directions, fontsize=10.5, color=TEXT_DARK)
for label in y_labels:
    label.set_multialignment('center')

ax_left.set_xlim(0, 100)
ax_left.set_xticks([0, 25, 50, 75, 100])
ax_left.set_xticklabels(['0%', '25%', '50%', '75%', '100%'], fontsize=9, color=TEXT_LIGHT)
ax_left.tick_params(axis='y', length=0, pad=8)
ax_left.tick_params(axis='x', colors=TEXT_LIGHT, length=0)

for spine_name in ['top', 'right', 'left']:
    ax_left.spines[spine_name].set_visible(False)
ax_left.spines['bottom'].set_color(DIVIDER)
ax_left.spines['bottom'].set_linewidth(0.7)

legend = ax_left.legend(loc='lower center', bbox_to_anchor=(0.5, -0.18),
                        ncol=3, frameon=False, fontsize=8.8,
                        handlelength=1.5, handleheight=1, columnspacing=1.5)
for text in legend.get_texts():
    text.set_color(TEXT_GRAY)


# ============================================================================
# Helper to draw a port sub-panel (used twice: imports top, exports bottom)
# ============================================================================
def draw_port_subpanel(ax, ports_df, title_text, title_y, ax_left_fig=0.69):
    """Draw a horizontal bar chart of top-10 ports inside the given axes."""
    df_sorted = ports_df.sort_values("share_pct", ascending=True).reset_index(drop=True)
    names = df_sorted["port_display"].tolist()
    shares = df_sorted["share_pct"].tolist()

    # Top-1 (largest, last in ascending list) → darker color
    colors = [COLOR_PORT] * len(names)
    colors[-1] = COLOR_PORT_TOP

    y_positions = range(len(names))
    ax.barh(y_positions, shares, color=colors,
            edgecolor='white', linewidth=1.0, height=0.7)

    for i, s in enumerate(shares):
        ax.text(s + 0.5, i, f'{s:.0f}%',
                va='center', ha='left',
                fontsize=9, color=TEXT_DARK, fontweight='bold')

    ax.set_yticks(list(y_positions))
    ax.set_yticklabels(names, fontsize=9, color=TEXT_DARK)
    ax.tick_params(axis='y', length=0, pad=4)
    ax.set_xlim(0, max(shares) * 1.40)
    ax.set_xticks([])

    for spine_name in ['top', 'right', 'bottom', 'left']:
        ax.spines[spine_name].set_visible(False)

    # Mini title centered over visual block
    fig.text(0.74, title_y, title_text,
             ha='center', fontsize=10.5, color=TEXT_DARK, fontweight='bold')


# ============================================================================
# PANEL RIGHT TOP — Imports (China → Brazil) top 10
# ============================================================================
ax_right_top = fig.add_axes([0.69, 0.49, 0.27, 0.24])
ax_right_top.set_facecolor('#FFFFFF')
draw_port_subpanel(
    ax_right_top, ports_imports,
    f"Imports from China — top 10 ports  ·  HHI = {HHI_IMP:,.0f}",
    title_y=0.755,
)

# ============================================================================
# PANEL RIGHT BOTTOM — Exports (Brazil → China) top 10
# ============================================================================
ax_right_bot = fig.add_axes([0.69, 0.18, 0.27, 0.24])
ax_right_bot.set_facecolor('#FFFFFF')
draw_port_subpanel(
    ax_right_bot, ports_exports,
    f"Exports to China — top 10 ports  ·  HHI = {HHI_EXP:,.0f}",
    title_y=0.445,
)

# ============================================================================
# FOOTER
# ============================================================================
fig.add_artist(plt.Line2D([0.06, 0.94], [0.115, 0.115],
                          color=DIVIDER, linewidth=0.8,
                          transform=fig.transFigure))

fig.text(0.5, 0.075,
         "Scope:  Brazil–China bilateral trade 2025, maritime mode only  ·  3-bucket classification by HS2 chapter  ·  HHI = Σ(share%)²",
         ha='center', fontsize=8, color=TEXT_LIGHT)

fig.text(0.06, 0.035,
         "Source:  ComexStat / MDIC 2025  ·  ANTAQ 2025",
         ha='left', fontsize=8.5, color=TEXT_SOURCE)

fig.text(0.94, 0.035,
         "github.com/hugopedro-ds/brazilian-maritime-analysis-2025",
         ha='right', fontsize=8.5, color=TEXT_SOURCE)

plt.savefig(OUT_PNG, dpi=100, facecolor='#FFFFFF', edgecolor='none')
print(f"Saved: {OUT_PNG}")
